# These are supported funding model platforms

github: [xiaozhu2007] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: xiaozhu2007 # Replace with a single Patreon username
ko_fi: xiaozhu2007 # Replace with a single Ko-fi username
custom: ['https://afdian.net/a/xiaozhu2021', 'https://afdian.net/a/HackPig520'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
