name: Python application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
  - cron: "57 */12 * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install
      run: |
        sudo python -m pip install --upgrade pip
        sudo pip install argparse scapy wget pathlib
        if [ -f requirements.txt ]; then sudo pip install -r requirements.txt; fi
    - name: Run
      run: |
        sudo python dns-spoofable.py -o output.txt
    - name: Push
      run: |
        git version > /dev/null
        sleep 1
        git config --global user.name "HelloTools-bot"
        git config --global user.email "3356136957@qq.com"
        git add output.txt
        git commit --allow-empty -m ":star: update: `date '+%Y-%m-%d %H:%M:%S'` [skip ci]"
        sleep 1
        sudo git push
        echo Success!
