name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install argparse scapy wget pathlib
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run with python
      run: |
        python dns-spoofable.py -o output.txt
